export const APP_URL = 'http://eskisehirseo.com/puss-demo'
export const API_URL = APP_URL+'/index.php/api'
export const APP_NAME = 'EFRAHIM'
export const APP_SLUG = 'efrahim'
export const APP_LOGO = 'https://66.media.tumblr.com/a330d98ba819cf3fb204fcf9e2b3c204/tumblr_p1q9o0xN2o1wih5cfo3_250.png'
export const APP_CAT_IMG_PATH = APP_URL+'/uploads/admin/category/'
export const APP_BUSS_IMG_PATH = APP_URL+'/uploads/business/'